-- migrate:up
CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  phone_number VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL,
  account VARCHAR(200) NOT NULL,
  name VARCHAR(200) NOT NULL,
  password VARCHAR(200) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- migrate:down
DROP TABLE users;
